### PR TITLE
Update DBStorage and FileStorage

### PR DESCRIPTION
**Pull request by dawitgetuu**
we are done the request to add and Update DBStorage and FileStorage, adding two new methods to easily usage of our group project ,the project is already going we are working on it.it

### CODE REVIEW

**Comment by dawitgetuu** [comment]
good job,

**Comment by Chidubemkingsley** [comment]
We succeeded in creating the storage_get_count branch for both the DBStorage and File storage by adding two methods thsat was utilized in the project demand.

**Review by dawitgetuu — COMMENTED** [review]
that is good, nice work

**Comment by Chidubemkingsley** [comment]
Good job

**Comment by Chidubemkingsley** [comment]
Good one

**Pull request merged**
